datadecide_models = [
    "allenai/DataDecide-dclm-baseline-4M",
    "allenai/DataDecide-dclm-baseline-20M",
    "allenai/DataDecide-dclm-baseline-60M",
    "allenai/DataDecide-dclm-baseline-90M",
    "allenai/DataDecide-dclm-baseline-150M",
    "allenai/DataDecide-dclm-baseline-300M",
    "allenai/DataDecide-dclm-baseline-530M",
    "allenai/DataDecide-dclm-baseline-750M",
    "allenai/DataDecide-dclm-baseline-1B",

    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-4M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-20M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-60M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-90M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-150M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-300M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-530M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-750M",
    "allenai/DataDecide-dclm-baseline-25p-dolma1.7-75p-1B",

    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-4M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-20M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-60M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-90M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-150M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-300M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-530M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-750M",
    "allenai/DataDecide-dclm-baseline-50p-dolma1.7-50p-1B",

    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-4M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-20M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-60M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-90M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-150M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-300M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-530M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-750M",
    "allenai/DataDecide-dclm-baseline-75p-dolma1.7-25p-1B",

    "allenai/DataDecide-dclm-baseline-qc-10p-4M",
    "allenai/DataDecide-dclm-baseline-qc-10p-20M",
    "allenai/DataDecide-dclm-baseline-qc-10p-60M",
    "allenai/DataDecide-dclm-baseline-qc-10p-90M",
    "allenai/DataDecide-dclm-baseline-qc-10p-150M",
    "allenai/DataDecide-dclm-baseline-qc-10p-300M",
    "allenai/DataDecide-dclm-baseline-qc-10p-530M",
    "allenai/DataDecide-dclm-baseline-qc-10p-750M",
    "allenai/DataDecide-dclm-baseline-qc-10p-1B",

    "allenai/DataDecide-dclm-baseline-qc-20p-4M",
    "allenai/DataDecide-dclm-baseline-qc-20p-20M",
    "allenai/DataDecide-dclm-baseline-qc-20p-60M",
    "allenai/DataDecide-dclm-baseline-qc-20p-90M",
    "allenai/DataDecide-dclm-baseline-qc-20p-150M",
    "allenai/DataDecide-dclm-baseline-qc-20p-300M",
    "allenai/DataDecide-dclm-baseline-qc-20p-530M",
    "allenai/DataDecide-dclm-baseline-qc-20p-750M",
    "allenai/DataDecide-dclm-baseline-qc-20p-1B",

    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-4M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-20M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-60M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-90M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-150M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-300M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-530M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-750M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw2-1B",

    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-4M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-20M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-60M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-90M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-150M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-300M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-530M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-750M",
    "allenai/DataDecide-dclm-baseline-qc-7p-fw3-1B",

    "allenai/DataDecide-dclm-baseline-qc-fw-10p-4M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-20M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-60M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-90M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-150M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-300M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-530M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-750M",
    "allenai/DataDecide-dclm-baseline-qc-fw-10p-1B",

    "allenai/DataDecide-dclm-baseline-qc-fw-3p-4M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-20M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-60M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-90M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-150M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-300M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-530M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-750M",
    "allenai/DataDecide-dclm-baseline-qc-fw-3p-1B",

    "allenai/DataDecide-dolma1_6plus-4M",
    "allenai/DataDecide-dolma1_6plus-20M",
    "allenai/DataDecide-dolma1_6plus-60M",
    "allenai/DataDecide-dolma1_6plus-90M",
    "allenai/DataDecide-dolma1_6plus-150M",
    "allenai/DataDecide-dolma1_6plus-300M",
    "allenai/DataDecide-dolma1_6plus-530M",
    "allenai/DataDecide-dolma1_6plus-750M",
    "allenai/DataDecide-dolma1_6plus-1B",
]
